name: Build Dolphin (Windows only)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        c_compiler: [cl]
        cpp_compiler: [cl]

    steps:
    - name: Checkout Dolphin with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Cache build
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/build
          ${{ github.workspace }}/Externals
        key: ${{ runner.os }}-${{ matrix.build_type }}-${{ hashFiles('CMakeLists.txt') }}

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build (parallel)
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }} -- /m

    # Tests opcionales: solo en PRs
    - name: Test
      if: github.event_name == 'pull_request'
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }} --output-on-failure -j2

    - name: Upload Dolphin executable + DLLs
      uses: actions/upload-artifact@v4
      with:
        name: dolphin-windows-${{ matrix.build_type }}
        path: |
          ${{ steps.strings.outputs.build-output-dir }}/Binary/x64/${{ matrix.build_type }}/dolphin-emu.exe
          ${{ steps.strings.outputs.build-output-dir }}/Binary/x64/${{ matrix.build_type }}/*.dll
